#! /bin/sh
# /etc/init.d/gero: Autostart Geroix Gero.

### BEGIN INIT INFO
# Provides: gero
# Required-Start: $all
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start Geroix Gero at boot time
# Description: Start Geroix Gero at boot time.
### END INIT INFO

case "$1" in
 start)
  echo "Starting Gero"
  sh /opt/geroix/gero/start.sh
  echo "Starting Gero done"
  ;;

 stop)
  echo "Stopping Gero"
  ret=$(ps aux | grep 'node app.js' | awk '{print $2}')
  echo "Removing node by running >kill ${ret}"
  kill ${ret}
  ;;


 restart)
  echo "Stopping Gero"
  ret=$(ps aux | grep 'node app.js' | awk '{print $2}')
  echo "Removing node by running >kill ${ret}"
  sh /opt/geroix/gero/start.sh
  echo "Starting Gero done"
  ;;

 *)
  echo "Usage: /etc/init.d/gero {start|stop|restart}"
  exit 1
  ;;
esac

exit 0
